version: '2'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./files:/var/www
    ports:
      - "8080:80"
    command: nginx -g 'daemon off;'
    links:
      - php
      - mariadb
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./files:/var/www/html
      - ./files:/var/www
    links:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=test_pass
    volumes:
      - ./mysql/database:/var/lib/mysql
