version: '2'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./files:/var/www
    ports:
      - "8080:80"
    command: nginx -g 'daemon off;'
    links:
      - php
  php:
    image: php:7.1-fpm-alpine
    volumes:
      - ./files:/var/www/html
      - ./files:/var/www
